- name: Install Ruby dev/gems
  apt:
    pkg: "{{item}}"
  with_items:
    - build-essential={{ build_essential_version }}
    - ruby-dev={{ ruby_dev_version }}

- name: Add td-agent key
  apt_key:
    url: "{{ tdagent_apt_key }}"

- name: Add td-agent repository
  apt_repository:
    repo: "{{ tdagent_repo }}"

- name: Install td-agent
  apt:
    name: td-agent={{ td_agent_version }}

- name: Make sure td-agent service is running
  service:
    state: started
    name: td-agent
